qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1 50
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 51 100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 101 150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 151 200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 201 250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 251 300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 301 350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 351 400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 401 450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 451 500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 501 550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 551 600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 601 650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 651 700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 701 750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 751 800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 801 850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 851 900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 901 950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 951 1000
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1001 1050
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1051 1100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1101 1150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1151 1200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1201 1250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1251 1300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1301 1350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1351 1400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1401 1450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1451 1500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1501 1550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1551 1600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1601 1650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1651 1700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1701 1750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1751 1800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1801 1850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1851 1900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1901 1950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 1951 2000
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2001 2050
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2051 2100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2101 2150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2151 2200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2201 2250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2251 2300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2301 2350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2351 2400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2401 2450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2451 2500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2501 2550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2551 2600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2601 2650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2651 2700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2701 2750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2751 2800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2801 2850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2851 2900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2901 2950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 2951 3000
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3001 3050
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3051 3100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3101 3150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3151 3200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3201 3250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3251 3300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3301 3350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3351 3400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3401 3450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3451 3500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3501 3550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3551 3600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3601 3650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3651 3700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3701 3750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3751 3800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3801 3850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3851 3900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3901 3950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 3951 4000
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4001 4050
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4051 4100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4101 4150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4151 4200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4201 4250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4251 4300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4301 4350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4351 4400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4401 4450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4451 4500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4501 4550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4551 4600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4601 4650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4651 4700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4701 4750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4751 4800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4801 4850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4851 4900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4901 4950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code_MED/sge_script/extract.sgejob.sh 4951 4992
